# Generated by Django 3.2.3 on 2021-06-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='desc',
            field=models.TextField(default='desc = models.TextField()'),
            preserve_default=False,
        ),
    ]
